# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(:email => "admin@grapewitz.com", :password => "password")

Region.create!(:name => 'Unknown')
Region.create!(:name => 'France')
Region.create!(:name => 'Italy')
Region.create!(:name => 'Germany')
Region.create!(:name => 'US')
Region.create!(:name => 'NZ')
Region.create!(:name => 'Australia')
Region.create!(:name => 'Spain')
Region.create!(:name => 'Portugal')
Region.create!(:name => 'US-California')
Region.create!(:name => 'France-Loire')
Region.create!(:name => 'Italy-Tuscany')


Brand.create(:name => 'Home Brew')

Store.create(:name => 'The Web')

Variety.create(:name => 'Burgundy', :color => 1, :fizz => 0)
Variety.create(:name => 'Bordeaux', :color => 1, :fizz => 0)
Variety.create(:name => 'Chardonnay', :color => 0, :fizz => 0)
Variety.create(:name => 'Champagne', :color => 0, :fizz => 1)
Variety.create(:name => 'Chablis', :color => 0, :fizz => 0)
Variety.create(:name => 'Rose', :color => 2, :fizz => 0)
Variety.create(:name => 'Cava', :color => 0, :fizz => 1)
Variety.create(:name => 'Cote du Rhone', :color => 1, :fizz => 0)
Variety.create(:name => 'Montepulciano', :color => 1, :fizz => 0)
Variety.create(:name => 'Chianti', :color => 1, :fizz => 0)
Variety.create(:name => 'Sauvignon Blanc', :color => 0, :fizz => 0)
Variety.create(:name => 'Shiraz', :color => 1, :fizz => 0)
Variety.create(:name => 'Pinot Noir', :color => 1, :fizz => 0)
Variety.create(:name => 'Zinfandel', :color => 1, :fizz => 0)
Variety.create(:name => 'Cabernet Sauvignon', :color => 1, :fizz => 0)
Variety.create(:name => 'Super Tuscan', :color => 1, :fizz => 0)
Variety.create(:name => 'Valpolicella', :color => 1, :fizz => 0)
Variety.create(:name => 'Nero d\'Avola', :color => 1, :fizz => 0)
Variety.create(:name => 'Amarone', :color => 1, :fizz => 0)
Variety.create(:name => 'Prosecco', :color => 0, :fizz => 1)
Variety.create(:name => 'Cabernet Franc', :color => 1, :fizz => 0)
Variety.create(:name => 'Barolo', :color => 1, :fizz => 0)
Variety.create(:name => 'White Bordeauz', :color => 0, :fizz => 0)
Variety.create(:name => 'Vouvrey', :color => 0, :fizz => 0)
Variety.create(:name => 'Chenin Blanc', :color => 0, :fizz => 0)
Variety.create(:name => 'Reisling', :color => 0, :fizz => 0)
Variety.create(:name => 'Moscato', :color => 0, :fizz => 0)
Variety.create(:name => 'Fiano', :color => 0, :fizz => 0)
Variety.create(:name => 'Viognier', :color => 0, :fizz => 0)
Variety.create(:name => 'Pino Blanc', :color => 0, :fizz => 0)
Variety.create(:name => 'Pouilly Fume', :color => 0, :fizz => 0)
Variety.create(:name => 'Sancerre', :color => 0, :fizz => 0)
